name: hyrule
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  floor: ^1.4.2
  sqflite: ^2.3.0
  http: ^1.1.0
  dio: ^5.3.2
  localization: ^2.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2 
  build_runner: ^2.4.8

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Philosopher
      fonts:
        - asset: assets/fonts/Philosopher-Regular.ttf
        - asset: assets/fonts/Philosopher-Bold.ttf
        - asset: assets/fonts/Philosopher-BoldItalic.ttf
        - asset: assets/fonts/Philosopher-Italic.ttf
          style: italic